<?php $this->headTitle($this->translate('MYBOOKMARKS')); ?>

<section id="core">

    <ul id="bookmarks" data-role="listview" data-autodividers="true" data-filter="true" data-inset="true">

        <?php foreach ($this->tags as $key => $value) { ?>

            <li>
                <a href="/bookmarksbytag/<?php echo $this->escape($key); ?>" title="<?php echo $this->escape($value); ?>">
                    <?php echo $this->escape($value); ?>
                </a>
            </li>

        <?php } ?>

    </ul>

</section>



