<?php $this->headTitle($this->translate('MYBOOKMARKS')); ?>

<section id="core-box">
    
    <div id="bookmarks_container">
        
        <div id="tags_list">

            <ul id="bookmarks" data-role="listview" data-autodividers="true" data-filter="true" data-inset="true" data-filter-placeholder="Filter tags...">

                <?php foreach ($this->tags as $key => $value) { ?>

                    <li>
                        <a href="/mybookmarks/<?php echo $this->escape($value); ?>" title="<?php echo $this->escape($value); ?>" data-chris-tag-key="<?php echo $this->escape($key); ?>">
                            <?php echo $this->escape($value); ?>
                        </a>
                    </li>

                <?php } ?>

            </ul>

        </div>
        
    </div>

</section>



