<?php $this->headTitle($this->translate('ADMIN_INDEX')); ?>

<a href="<?php echo $this->url(array(), 'articleadminindex'); ?>" class="btn btn-mini btn-primary"><?php echo $this->translate('ADMIN_ARTICLE_MANAGE'); ?></a>
<br /><br />
<a href="<?php echo $this->url(array(), 'articlecommentsadminindex'); ?>" class="btn btn-mini btn-primary"><?php echo $this->translate('ADMIN_ARTICLE_COMMENT_MANAGE'); ?></a>
<br /><br />
<a href="<?php echo $this->url(array(), 'bookmarkadminindex'); ?>" class="btn btn-mini btn-primary"><?php echo $this->translate('ADMIN_BOOKMARK_MANAGE'); ?></a>
<br /><br />
<a href="<?php echo $this->url(array(), 'projectsadminindex'); ?>" class="btn btn-mini btn-primary"><?php echo $this->translate('ADMIN_PROJECTS_MANAGE'); ?></a>
<br /><br />
<a href="<?php echo $this->url(array(), 'readinglistadminindex'); ?>" class="btn btn-mini btn-primary"><?php echo $this->translate('ADMIN_READINGLIST_MANAGE'); ?></a>
<br /><br />
<a href="<?php echo $this->url(array(), 'useradminindex'); ?>" class="btn btn-mini btn-primary"><?php echo $this->translate('ADMIN_USER_MANAGE'); ?></a>
<br /><br />